spring:
  application:
    name: notice_management
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  file:
    save:
      path: /Users/qwert/notice_management/

  data:
    redis:
      host: localhost
      port: ${LOCAL_REDIS_PORT}

  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/notice_management?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}